# Name the workflow
name: ARM Tests
on:
 pull_request:
  branches:
    - master

jobs:
  test_arm_templates:
    runs-on: ubuntu-latest
    name: Run ARM TTK
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run ARM TTK
        uses: ./.github/actions
        id: action




        